### ISSUE TITLE
Setting up compute environment

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/Cogent3Workshop#2]
- Docker / Colima installations
- Instructions per OS
- VS Code, or another approach to running Jupyter
- VS Code extensions

Put other points below

**Comment by GavinHuttley** [comment]
Peter Minogue's suggestion was to use conda. This can work, but on Windows I am not sure about the terminal experience.

**Comment by GavinHuttley** [comment]
@khiron I have started a wiki page for [comp setup](https://github.com/cogent3/Cogent3Workshop/wiki/Computer-Setup). Our essential requirements are that a users VS Code terminal connects to the VM so they can run commands. Similarly, that when they initiate Jupyter notebooks it is connecting to the VM.
I probably need to demo what's required so you can establish config.

**Comment by khiron** [comment]
I have a working document in /docker/README.md pending translation to the wiki 

It includes how to do everything from VS Code (build/run/attach to container) 

Also to build and run from the host OS and work with notebooks in the host OS's browser

**Comment by khiron** [comment]
README.md has been translated to the wiki.
