### ISSUE TITLE
LO - 2 - Sampling ensembl

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/Cogent3Workshop#24]
This will introduce the (currently under development) command line interface to Ensembl data.

## Installation

Within the VS Code terminal, with your virtual environment activated, install `EnsemblLite` as
```
pip install git+https://github.com/cogent3/EnsemblLite.git
```

## Notes
We will cover:

- Downloading
- Installing
- Data summaries
- Selecting related sequence types
- Selecting aligned sequences with position types masked

**Comment by KatherineCaley** [comment]
@GavinHuttley please put content from this issue as a comment in #43 😄
