### ISSUE TITLE
LO - 2 - Getting data

### ISSUE THREAD

**Issue by KatherineCaley** [cogent3/Cogent3Workshop#25]
- Published GenBank ID's (e.g. REFSOIL)
- Ensembl downloading and Installing

**Comment by GavinHuttley** [comment]
yapeng to help with the Duchene problem data after submitting

**Comment by KatherineCaley** [comment]
### Trying to get a published reference dataset with REFSOIL

- link to the publication (https://www.nature.com/articles/ismej2016168#Sec2) 
- what we cant get:
  - genbank sequences
  - screen grab of the process trying to get the data 
-  what we can get:
  - list of NCBI accession numbers
  - screen grab of the process of using the NCBI command line tool
  - script to download genbank files from a list of NCBI accession numbers
