### ISSUE TITLE
LO - 3 - Identifying and dealing with data issues

### ISSUE THREAD

**Issue by KatherineCaley** [cogent3/Cogent3Workshop#27]
- inconsistent meta-data (data wrangling REFSOIL GenBank files)
  - demonstrate using annotation_db
  - explore using dotplots (e.g., 2 sequences that claim to be the same, dotplot to see if this is the case, ungapped smith waterman score -> p-value)
- File formats issues
  - Duchene phylip formats, solving using bad_phylip app (Gavin to upload this app)
  - extremely long fasta sequence labels (e.g. making sure you can collate genomes from one species)

**Comment by GavinHuttley** [comment]
the bad phylip loader app
```python
import re
from collections import defaultdict
from cogent3.app.composable import define_app, LOADER
from cogent3.app import typing as c3types
from cogent3 import make_aligned_seqs, open_data_store

_wspace = re.compile(r"\s+")

@define_app(app_type=LOADER)
def load_bad_phylip(path: c3types.IdentifierType, moltype="dna") -> c3types.AlignedSeqsType:
    data = path.read()  # interim
    data = data.splitlines()
    num_seqs, seq_len = [int(e) for e in data[0].split()]
    labels = []
    seqs = defaultdict(list)
    seq_num = 0
    getting_labels = True
    for line in data[1:]:
        line = line.strip()
        if not line:
            continue
        
        if getting_labels:
            label, line = _wspace.split(line, maxsplit=1)
            labels.append(label)
            if len(labels) == num_seqs:
                getting_labels = False
        else:
            label = labels[seq_num]
            seq_num += 1
            if seq_num == num_seqs:
                seq_num = 0

        seq = _wspace.sub("", line)
        seqs[label].append(seq)
    
    seqs = {l: "".join(s) for l, s in seqs.items()}
    lengths = {len(s) for s in seqs.values()}
    assert lengths == {seq_len}
    return make_aligned_seqs(data=seqs, moltype=moltype)

if __name__ == "__main__":    
    # works on Gavin's machine!
    dstore = open_data_store("~/Desktop/Inbox", suffix="phy", mode="r")
    loader = load_bad_phylip()
    # just doing one file
    print(repr(loader(dstore[0])))
```
and some sample data
[locus-0.phy.zip](https://github.com/cogent3/Cogent3Workshop/files/13035774/locus-0.phy.zip)

**Comment by GavinHuttley** [comment]
@fredjaya can you find examples of fasta files with overloaded sequence labels and show how to use the `label_to_name` argument to `make_<un>aligned_seqs()` or `load_<un>aligned_seqs()` functions [docs are here](https://cogent3.org/doc/cookbook/loading_sequences.html#stripping-label-characters-on-loading).

Worth noting it's more difficult for a sequence from GenBank since the data is embedded within the features and doing a sequence rename can break the relationship to features in the `annotation_db`. (Discuss this with Kath.)

**Comment by fredjaya** [comment]
Will update this message as I come across new examples:
- https://www.ncbi.nlm.nih.gov/nuccore/MW854630.1?report=fasta

**Comment by fredjaya** [comment]
## Data
- Using sequence [EU244602.1](https://www.ncbi.nlm.nih.gov/nuccore/EU244602.1?report=fasta)
- Downloaded to file `data/EU244602.1.fa`

## Usage  

Loading in an unaligned sequence, with and without removing all label characters after the first whitespace:  
```python
from cogent3 import load_unaligned_seqs

fasta_file = "data/EU244602.1.fa"
unstripped_seq = load_unaligned_seqs(fasta_file, moltype="dna")
stripped_seq = load_unaligned_seqs(
        fasta_file, moltype="dna", label_to_name=lambda x: x.split()[0])
)

print(unstripped_seq)
print(stripped_seq)
```

>\>EU244602.1 Cornechiniscus lobatus from Egypt cytochrome oxidase subunit I-like
(COI) gene, partial sequence; mitochondrial                                    
GGTCAACAAATCATAAAGATATTGGCACTTTGTATTTTATTTTTGGGTTCTGATCTGCCT                   
CTGTCGGCTCTAGATTTAGACTTATTATTCGAACAGAATTGTCTCAACCTGGTATTTTTC                   
TTGGGGATGAGCATTTATATAATGTTTTGGTTACTTCCCACGCTTTAGTTATAATTTTCT                   
TTATAGTTATGCCAATTTTAATTGGAGGTTTTGGTAATTGATTAGTGCCCCTTATAATTG                   
GGGCTCCGGATATGGCGTTCCCTCGGATGAATAATTTGAGTTTTTGACTTTTACCACCTG                   
CTCTCATGCTACTTTTAATATCTTCTAATACTTATGCGGGGGCCGGAACCGGCTGGACTC                   
TTTATCCACCTCTATCAAGCTACTCAGGCCATTCTAATGTGACTGTTGATATAGCTATTT
TTTCTTTGCATATTGCCGGAGCTTCTTCTATTTTGGGTGCTATTAATTTTATTACTACTA
TTTTTAACATGCGCTCTTTATCTCTGAGTCTTGAAAATATAAGTTTATTTGTTTGATCTG
TTTTGATTACTGCCTTTTTACTTCTTTTTTCTCTACCTGTTTTAGCAGGTGGTATTACCA
TACTTTTAATAGATCGTAATTTTAATAGCTCATTTTTTGATCCTTCCGGGGGTGGTGATG
CCAATTCTTTTTCAGCANGAATTTTGATTTTTTGGTCACCCTGAAGTTTA
>
>\>EU244602.1
GGTCAACAAATCATAAAGATATTGGCACTTTGTATTTTATTTTTGGGTTCTGATCTGCCT
CTGTCGGCTCTAGATTTAGACTTATTATTCGAACAGAATTGTCTCAACCTGGTATTTTTC
TTGGGGATGAGCATTTATATAATGTTTTGGTTACTTCCCACGCTTTAGTTATAATTTTCT
TTATAGTTATGCCAATTTTAATTGGAGGTTTTGGTAATTGATTAGTGCCCCTTATAATTG
GGGCTCCGGATATGGCGTTCCCTCGGATGAATAATTTGAGTTTTTGACTTTTACCACCTG
CTCTCATGCTACTTTTAATATCTTCTAATACTTATGCGGGGGCCGGAACCGGCTGGACTC
TTTATCCACCTCTATCAAGCTACTCAGGCCATTCTAATGTGACTGTTGATATAGCTATTT
TTTCTTTGCATATTGCCGGAGCTTCTTCTATTTTGGGTGCTATTAATTTTATTACTACTA
TTTTTAACATGCGCTCTTTATCTCTGAGTCTTGAAAATATAAGTTTATTTGTTTGATCTG
TTTTGATTACTGCCTTTTTACTTCTTTTTTCTCTACCTGTTTTAGCAGGTGGTATTACCA
TACTTTTAATAGATCGTAATTTTAATAGCTCATTTTTTGATCCTTCCGGGGGTGGTGATG
CCAATTCTTTTTCAGCANGAATTTTGATTTTTTGGTCACCCTGAAGTTTA

**Comment by KatherineCaley** [comment]
bad phillip is ported to issue #37

**Comment by KatherineCaley** [comment]
data wrangling is in #28

**Comment by KatherineCaley** [comment]
collapsing this issue into #28

**Comment by KatherineCaley** [comment]
Closing as contented related to this issue will be described in #40
