### ISSUE TITLE
LO - 3 - Alignments

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/Cogent3Workshop#28]
- identifying divergent sequences prior to alignment and their relationships (using k-mer based tree estimation)
- using cogent3 to align, the app, memory, speed, parameters
- quantifying alignment quality using dotplots showing alignment path between most divergent sequences
- information plots, plotting gaps
- `Alignment.count_gaps_per_seq(induced_by, unique)`
- `Alignment.omit_bad_seqs()`

**Comment by KatherineCaley** [comment]
I have passed on some rough code to @fredjaya to document

**Comment by KatherineCaley** [comment]
Closing as contented related to this issue will be described in #40
