### ISSUE TITLE
c3 stickers

### ISSUE THREAD

**Issue by KatherineCaley** [cogent3/Cogent3Workshop#31]
two versions, one with just logo, one with QR code that goes to the GitHub (or to cogent3.org ?) 

@fredjaya to sort stickers 

@KatherineCaley to provide links to the svg files

**Comment by KatherineCaley** [comment]
png and svg file for full logo are [here](https://github.com/cogent3/cogent3.github.io/tree/develop/doc/_static)

**Comment by KatherineCaley** [comment]
[c3-qr-code.zip](https://github.com/cogent3/Cogent3Workshop/files/13149210/c3-qr-code.zip)

**Comment by fredjaya** [comment]
Quotes sent to radstickers

**Comment by fredjaya** [comment]
QR 40x40mm
150 - $145+gst
250 - $220+gst

Logo 100x40mm
250 - $220+gst
500 - $400+gst
For die cut, a 5mm border is required (which is thicker than usual)

Postage
$20+gst

**Comment by KatherineCaley** [comment]
@Vini2 how does this compare to the stickers you got made?

**Comment by Vini2** [comment]
@KatherineCaley I had 50 50x50mm printed for $69.99 (including GST and postage), but if was not the thick vinyl stickers I was expecting. They started fading after a few months.

**Comment by KatherineCaley** [comment]
@Vini2 thank you!! good to get a comparison 😇

**Comment by khiron** [comment]
This Brisbane service [ https://shop.eprintonline.com.au/vinyl-sticker-printing-australia/ ] will do 100 vinyl low tack stickers for $44 in 5 days.

Low tack is good if you are sticking them on the backs of laptop displays as they won't leave a residue when you remove them.

**Comment by GavinHuttley** [comment]
Stickers ordered!
