### ISSUE TITLE
backref from colima

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/Cogent3Workshop#32]
on the wiki page describing `colima` install add a backlink so users can navigate to the next step spot on the Computer Setup page.

**Comment by khiron** [comment]
I removed the stand-alone colima page as the wiki interface gives pages root level location in the content hierarchy, which looks weird.

I put the colima installation instructions nested (using <details><summary>) in the macOS section and nested Docker Desktop for Mac installation instructions at the same level using
