### ISSUE TITLE
Test of using devcontainers 

### ISSUE THREAD

**Issue by khiron** [cogent3/Cogent3Workshop#41]
[test_devcontainer.zip](https://github.com/cogent3/Cogent3Workshop/files/13330406/test_devcontainer.zip)

If you unzip this into a new folder and tell VS code to open that folder - you should be prompted to run it as a container and that will set up a full cogent3 envrironment

**Comment by rmcar17** [comment]
Works correctly on Windows Home 10 Home with docker (wsl2 backend) installed.
Took ~13 minutes to build the dev container on my HDD.

There was an issue with Pylance not working inside the notebook. I managed to fix this by running `Python: Clear Cache and Reload Window` in vscode's command palette.

**Comment by KatherineCaley** [comment]
Worked in about 3 minutes for me!
