### ISSUE TITLE
LO - 2 - Getting Data

### ISSUE THREAD

**Issue by KatherineCaley** [cogent3/Cogent3Workshop#43]
Draft content for block 2 of the workshop.

superset of issues #24, #25, #26. 

Getting data from:

- list of Genbank IDs (@KatherineCaley todo) 
- EnsemblLite (@GavinHuttley todo)
- Published data (@YapengLang todo and is actually part of LO- 4)

**Comment by KatherineCaley** [comment]
## Genbank 
### Trying to get a published reference dataset with REFSOIL

- link to the publication (https://www.nature.com/articles/ismej2016168#Sec2) 
- what **we want**: 
   - genome sequences and **their annotations**. I’m assuming the motivation for why annotations are necessary will have been mainly covered by this point. 
   - i.e., we want the genbank files. Explain the general form of a genbank file. 
- what we **can't get**:
  - genbank sequences
  - screen grab of the process trying to get the data 
-  what we **can get**:
   - list of NCBI accession numbers 
   - screen grab of the process of using the NCBI command line tool
- how we **can get** what **we want**:
   -  script to download genbank files from a list of NCBI accession numbers

**Comment by GavinHuttley** [comment]
# Ensembl

This will introduce the (currently under development) command line interface to Ensembl data.


## Installation

Within the VS Code terminal, with your virtual environment activated, install `EnsemblLite` as
```
pip install git+https://github.com/cogent3/EnsemblLite.git
```

## Notes
We will cover:

- Downloading
- Installing
- Data summaries
- Selecting related sequence types
- Selecting aligned sequences with position types masked

**Comment by fredjaya** [comment]
## Downloading GenBank files from a list of accession numbers 

`download_genbank.py` takes a file with a list of NCBI accession numbers and downloads the associated GenBank file. Files are downloaded asynchronously for speed. 

### Installation

Create `venv`
```bash
$ mkdir venv
$ python3 -m venv venv/
$ source venv/bin/activate
$ pip install cogent3 rich click unsync
```

### Example usage

- For help and options
```bash
$ python3 download_genbank.py
Usage: download_genbank.py [OPTIONS]

  downloads limit accessions from GenBank

Options:
  -p, --path PATH      path to genbank accession file  [required]
  -o, --outdir PATH    path to write genbank formatted sequence files
                       [required]
  -l, --limit INTEGER  number of accessions to download  [default: 10]
  --help               Show this message and exit.

```

- To download GenBank (.gb.gz) files for the first 10 accessions (default limit)
```
$ python3 download_genbank.py -p refsoil.txt -o refsoil 
```

### Notes

I commented out the use of `rich.track()` because the progress bar goes straight to 100% when using unsync.

@rmcar17

**Comment by rmcar17** [comment]
Slightly revamped genbank downloader with modified README based on the above by Fred.
[genbank_downloader.zip](https://github.com/cogent3/Cogent3Workshop/files/13343403/genbank_downloader.zip)

Important @khiron `click` needs to be added to the python pip installation in the docker file.

Instructions for wiki (taken from the README):

## Downloading GenBank files from a list of accession numbers 

`download_genbank.py` takes a file with a list of NCBI accession numbers and downloads the associated GenBank file. Files are downloaded asynchronously for speed.

### Example usage

- For help and options
```bash
$ python download_genbank.py
Usage: download_genbank.py [OPTIONS]

  downloads limit accessions from GenBank

Options:
  -p, --path PATH      path to genbank accession file  [required]
  -o, --outdir PATH    path to write genbank formatted sequence files
                       [required]
  -l, --limit INTEGER  number of accessions to download  [default: 10]
  --help               Show this message and exit.

```

- To download GenBank (.gb.gz) files for the first 10 accessions (default limit)
```bash
$ python download_genbank.py -p refsoil_id.txt -o refsoil
```

- To download GenBank (.gb.gz) files for the first 20 accessions
```bash
$ python download_genbank.py -p refsoil_id.txt -o refsoil -l 20
```

> **Note**
> Ensure the command is executed from the same directory as `download_genbank.py`. 
> You may need to run `cd genbank_downloader` first.

**Comment by fredjaya** [comment]
I'll do the screen grab of trying to get the refsoil data

**Comment by fredjaya** [comment]
https://github.com/cogent3/Cogent3Workshop/assets/36436914/b9a70c8a-db6a-4304-b421-d1509f8ca092


https://github.com/cogent3/Cogent3Workshop/assets/36436914/9358f8aa-732e-471a-9f48-0948511186b2

**Comment by fredjaya** [comment]
Screen casts for the figshare and python script methods on [Dropbox](https://www.dropbox.com/scl/fo/c9zcxj93gigy7ltbl42x1/h?rlkey=4s545x5vz759bpcwl4s4niuks&dl=0).

**Comment by GavinHuttley** [comment]
@rmcar17 and @fredjaya rather than remove using `track()`, change usage to `track(..., transient=True)` and the progress bar disappears when completed. Why do this? If someone on a slow network, that progress bar is useful!

**Comment by rmcar17** [comment]
@GavinHuttley below is a modified version of the genbank downloader using click's progressbar in a thread safe manner. Our initial experience was that rich's track did not work with unsync.

[genbank_downloader.zip](https://github.com/cogent3/Cogent3Workshop/files/13387072/genbank_downloader.zip)
