### ISSUE TITLE
Installing the cogent3 workshop environment on a Mac

### ISSUE THREAD

**Issue by khiron** [cogent3/Cogent3Workshop#44]
First draft of screen capture of the process

https://github.com/cogent3/Cogent3Workshop/assets/1835007/d554594e-c08c-4573-9c1e-bc8764de5cb3

**Comment by fredjaya** [comment]
@fredjaya to:
- [ ] Follow the install process on linux
- [ ] Record screencast
- [ ] Provide voice over

**Comment by khiron** [comment]
You can do the voice over for the linux install if you want.  But if you are running out of time I don't mind doing it.  

I'd do the screencast too except I got rid of my linux boot when WSL became an option.

**Comment by fredjaya** [comment]
Thanks, will let you know how I go. Also I forgot whether you mentioned if it was ok to go ahead with the screencast, or to wait until the next version of the image?

**Comment by khiron** [comment]
It won't make any difference to how the install looks.  Just an extra line of text flying past as the click python library is installed.  

You can screen cast an install with the existing devcontainer.  

The only reason we'd have to redo it is if we find something else that needs to be done manually during the install.

**Comment by khiron** [comment]
Just as I said that I realised that there is some way I can improve the UX - by telling the user when everything is set up and ready to go.  I've just made an update to the devcontainer.json that tells the user when everything is finished getting built and run.

![image](https://github.com/cogent3/Cogent3Workshop/assets/1835007/457c82c5-46e8-429b-9352-a2022c91c789)


I'm about to upload a new devcontainer.  But if you have already started to do the install, no big deal.

**Comment by fredjaya** [comment]
Got it working on linux but ran into an error when opening the devcontainer:
```
Error: ENOENT: no such file or directory, open '/home/frederickjaya/Downloads/Cogent3_Workshop_2023/.devcontainer/Dockerfile'
```

Solved with `mv DockerFile Dockerfile` - should I include this in the screencast, or is there a better fix?
