### ISSUE TITLE
Flowchart wrangling and checking data

### ISSUE THREAD

**Issue by khiron** [cogent3/Cogent3Workshop#6]
![image](https://github.com/cogent3/Cogent3Workshop/assets/1835007/bae6cb53-2f07-42a5-81d9-8e8290dfc805)

**Comment by khiron** [comment]
```mermaid
graph LR
    gbid[Published Genbank Identifiers] --> gb[Genbank] --> QC --> wrangled[wrangled checked data]
    online[published online data set] --> downloaded[downloaded data set] -->QC
    Ensemble-->build-->sample-->QC
```

**Comment by KatherineCaley** [comment]
![richard-merman](https://github.com/cogent3/Cogent3Workshop/assets/69446461/b6235717-1446-442b-a159-9dd5f729adba)

**Comment by khiron** [comment]
I think we need to flesh out the process of QC with sample steps required to check data is consistent and appropriate for use and then show each point in this pipeline where cogent3 can be used.

**Comment by GavinHuttley** [comment]
thanks @khiron !
